### ISSUE TITLE
Doesn't actually install anything if no zipChoice is promted.

### ISSUE THREAD

**Issue by danilaml** [RaspberryLime123/AONS-ENSU#1]
Looks like `set ONS_N=unset` remains `unset` if there is only a single .zip archive so the script tries to then `unzip unset` and silently fails (reports success without doing anything).

**Comment by RaspberryLime123** [comment]
Thank you for leaving such a specific issue. It helped a lot! It's fixed now, and I'm about to update the release

**Comment by RaspberryLime123** [comment]
Thank you for leaving such a specific issue. It helped a lot! It's fixed now, and I'm about to update the release
